// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CollectionMeta {
    "database": string;
    "collection": string;
    "replicaNum": number;
    "shardNum": number;
    "description": string;
    "fields": FieldMeta[] | null;
    "indexes": IndexMeta[] | null;
}

export interface FieldMeta {
    "fieldName": string;
    "fieldType": string;
    "fieldUsage": string;
    "primaryKey": boolean;
    "description": string;
}

export interface IndexMeta {
    "fieldName": string;
    "indexType": string;
    "metricType": string;
    "params": { [_ in string]?: any } | null;
}

export interface QueryDocumentResponse {
    "code": number;
    "msg": string;
    "count": number;
    "documents": ({ [_ in string]?: any } | null)[] | null;
}
