// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CollectionMeta {
    "database": string;
    "collection": string;
    "replicaNum": number;
    "shardNum": number;
    "description"?: string;
    "fields"?: FieldMeta[] | null;
    "indexes"?: IndexColumn[] | null;
    "isAiCollection"?: boolean;
}

export interface DatabaseDetail {
    "name": string;

    /**
     * "base" or "ai"
     */
    "dbType": string;
    "createTime"?: string;
}

export interface FieldMeta {
    "fieldName": string;
    "fieldType": string;
    "fieldUsage"?: string;
    "primaryKey"?: boolean;
    "description"?: string;
}

export interface IndexColumn {
    "fieldName"?: string;
    "fieldType"?: string;
    "indexType"?: string;
    "dimension"?: number;
    "metricType"?: string;
    "indexedCount"?: number;
    "params"?: { [_ in string]?: any } | null;
}

export interface QueryDocumentResponse {
    "code": number;
    "msg": string;
    "count": number;
    "documents": ({ [_ in string]?: any } | null)[] | null;
}

export interface UpdateDocumentQuery {
    "documentIds"?: string[] | null;
    "documentSetIds"?: string[] | null;
    "documentSetNames"?: string[] | null;
    "filter"?: string;
}
