// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DeleteConnection(id: string): $CancellablePromise<void> {
    return $Call.ByID(4051920909, id);
}

export function ListConnections(): $CancellablePromise<storage$0.ConnectionConfig[] | null> {
    return $Call.ByID(1315905871);
}

export function SaveConnection(cfg: storage$0.ConnectionConfig): $CancellablePromise<void> {
    return $Call.ByID(1614358563, cfg);
}

export function TestConnection(cfg: storage$0.ConnectionConfig): $CancellablePromise<$models.TestConnectionResult | null> {
    return $Call.ByID(717023674, cfg);
}
