// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface QueryDocumentsParams {
    "connectionId": string;
    "database": string;
    "collection": string;
    "limit": number;
    "offset": number;
    "filter": string;
}

export interface TestConnectionResult {
    "success": boolean;
    "message": string;
}
