// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as client$0 from "../client/models.js";

export interface QueryDocumentsParams {
    "connectionId": string;
    "database": string;
    "collection": string;
    "dbType"?: string;
    "limit": number;
    "offset": number;
    "filter": string;
}

export interface TestConnectionResult {
    "success": boolean;
    "message": string;
}

export interface UpdateDocumentParams {
    "connectionId": string;
    "database": string;
    "collection": string;
    "dbType"?: string;
    "query": client$0.UpdateDocumentQuery;
    "update": { [_ in string]?: any } | null;
}
