// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as client$0 from "../client/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DescribeCollection(connID: string, database: string, collection: string, dbType: string): $CancellablePromise<client$0.CollectionMeta | null> {
    return $Call.ByID(3631453886, connID, database, collection, dbType);
}

export function DropCollection(connID: string, database: string, collection: string, dbType: string): $CancellablePromise<void> {
    return $Call.ByID(3951098962, connID, database, collection, dbType);
}

/**
 * InvalidateCache removes the cached client for a given connection ID,
 * or purges all cached clients if connID is empty.
 */
export function InvalidateCache(connID: string): $CancellablePromise<void> {
    return $Call.ByID(1434046908, connID);
}

export function ListCollections(connID: string, database: string, dbType: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3927618840, connID, database, dbType);
}

export function ListDatabases(connID: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(488518623, connID);
}

export function ListDatabasesDetailed(connID: string): $CancellablePromise<client$0.DatabaseDetail[] | null> {
    return $Call.ByID(101094943, connID);
}

export function QueryDocuments(params: $models.QueryDocumentsParams): $CancellablePromise<client$0.QueryDocumentResponse | null> {
    return $Call.ByID(3724154521, params);
}

export function UpdateDocument(params: $models.UpdateDocumentParams): $CancellablePromise<void> {
    return $Call.ByID(255719591, params);
}
