// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ConnectionConfig {
    "id": string;
    "name": string;
    "url": string;
    "username": string;
    "apiKey": string;

    /**
     * in seconds
     */
    "timeout": number;
    "proxy"?: ProxyConfig;
    "sshTunnel"?: SSHTunnelConfig;
}

export interface ProxyConfig {
    "enabled": boolean;

    /**
     * "http", "socks5"
     */
    "type": string;
    "host": string;
    "port": number;
    "username"?: string;
    "password"?: string;
}

export interface SSHTunnelConfig {
    "enabled": boolean;
    "host": string;

    /**
     * default 22
     */
    "port": number;

    /**
     * e.g. root
     */
    "user": string;

    /**
     * "password", "key"
     */
    "authType": string;
    "password"?: string;

    /**
     * file path or PEM key text
     */
    "privateKey"?: string;
    "passphrase"?: string;
}
