// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ConnectionConfig {
    "id": string;
    "name": string;
    "url": string;
    "username": string;
    "apiKey": string;

    /**
     * in seconds
     */
    "timeout": number;
}
